###CREATE EVENT
POST http://localhost:5500/events/create
Content-Type: application/json


{
    "date": "2th July 2024",
    "duration": "2hrs Starting From 8AM",
    "Location": "South Africa",
    "Ticketsavailable": "400",
    "Singlesprice": 2000.00,
    "Groupsprice": 1000.00,
    "description": "GAME DRIVE: Enjoy nature",
    "image":"pexels-emma-bauso-1183828-2253842.jpg"
}

###UPDATE EVENT
PUT http://localhost:5500/events/4121a380-96ee-4003-b6ca-3b7caa02aeb1
Content-Type: application/json


{
    "date": "2th December 2024",
    "duration": "2hrs Starting From 8AM",
    "Location": "South Africa",
    "Ticketsavailable": "400",
    "Singlesprice": 2000.00,
    "Groupsprice": 1000.00,
    "description": "Ball Game",
    "image":"pexels-emma-bauso-1183828-2253842.jpg"
}

###DELETE EVENT
DELETE http://localhost:5500/events/1cca19ac-9749-476e-a328-91d13d4b69bd

###VIEW ALL EVENTS
GET http://localhost:5500/events/all-events
Content-Type: application/json

###VIEW ONE EVENT
GET http://localhost:5500/events/798067e9-f134-42d1-84e4-565cfc9a274a