###REGISTER USER
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "username": "Glen",
    "email": "glenA@example.com",
    "password": "glen12345"
}

###LOGIN USER
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "email": "timothy@example.com",
    "password": "timothy12345"
}

###UPDATE USER INFO
PUT http://localhost:5500/users/gamesmy177@gmail.com
Content-Type: application/json

{
    "password": "rodgers"
}


###SWITCH ROLE TO USER
PUT http://localhost:5500/users/switch-role
Content-Type: application/json

{
    "user_id":"f832ce5c-a784-4238-b170-1dc5887e263a"
}

###GET MANAGERS
GET http://localhost:5500/users/fetch-managers
Content-Type: application/json

### GET SINGLE MANAGER
GET http://localhost:5500/users/getManager/4cd4646e-a668-4dbf-9f3a-68706121f3c4
Content-Type: application/json

