CREATE TABLE event (event_id VARCHAR(255) PRIMARY KEY NOT NULL,
date VARCHAR(255) NOT NULL,
duration VARCHAR(50) NOT NULL,
Location VARCHAR(50) NOT NULL,
Ticketsavailable VARCHAR(255) NOT NULL,
Singlesprice DECIMAL(10,2) NOT NULL,
Groupsprice DECIMAL(10,2) NOT NULL,
description VARCHAR(255) NOT NULL,
)
DROP TABLE event

SELECT * FROM event

ALTER TABLE event ADD image VARCHAR(255) NOT NULL;