CREATE TABLE Users(user_id VARCHAR(255) PRIMARY KEY NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) DEFAULT 'user', status VARCHAR(50)DEFAULT 'active')
DROP TABLE Users

SELECT * FROM Users

ALTER TABLE Users ADD isWelcomed BIT DEFAULT (0) NOT NULL;

ALTER TABLE Users ADD isActive BIT DEFAULT (1) NOT NULL;
